/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_apache_spark_sgx_RingBuff */

#ifndef _Included_org_apache_spark_sgx_RingBuff
#define _Included_org_apache_spark_sgx_RingBuff
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_apache_spark_sgx_RingBuff
 * Method:    write_msg
 * Signature: (J[BI)Z
 */
JNIEXPORT jboolean JNICALL Java_org_apache_spark_sgx_RingBuff_write_1msg
  (JNIEnv *, jobject, jlong, jbyteArray, jint);

/*
 * Class:     org_apache_spark_sgx_RingBuff
 * Method:    read_msg
 * Signature: (J)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_apache_spark_sgx_RingBuff_read_1msg
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
