/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_apache_spark_sgx_RingBuffLibWrapper */

#ifndef _Included_org_apache_spark_sgx_shm_RingBuffLibWrapper
#define _Included_org_apache_spark_sgx_shm_RingBuffLibWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_apache_spark_sgx_shm_RingBuffLibWrapper
 * Method:    init_shm
 * Signature: (Ljava/lang/String;J)[J
 */
JNIEXPORT jlongArray JNICALL Java_org_apache_spark_sgx_shm_RingBuffLibWrapper_init_1shm
  (JNIEnv *, jclass, jstring, jlong);

/*
 * Class:     org_apache_spark_sgx_shm_RingBuffLibWrapper
 * Method:    write_msg
 * Signature: (J[B)Z
 */
JNIEXPORT jboolean JNICALL Java_org_apache_spark_sgx_shm_RingBuffLibWrapper_write_1msg
  (JNIEnv *, jclass, jlong, jbyteArray);

/*
 * Class:     org_apache_spark_sgx_shm_RingBuffLibWrapper
 * Method:    read_msg
 * Signature: (J)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_apache_spark_sgx_shm_RingBuffLibWrapper_read_1msg
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
