/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_apache_spark_sgx_RingBuffLibWrapper */

#ifndef _Included_org_apache_spark_sgx_shm_RingBuffLibWrapper
#define _Included_org_apache_spark_sgx_shm_RingBuffLibWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_apache_spark_sgx_shm_RingBuffLibWrapper
 * Method:    init_shm
 * Signature: (Ljava/lang/String;I)[J
 */
JNIEXPORT jlongArray JNICALL Java_org_apache_spark_sgx_shm_RingBuffLibWrapper_init_1shm
  (JNIEnv *, jclass, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
